name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        set -x
        
        pylint_output=$(pylint --score=y --rcfile .pylintrc $(git ls-files '*.py'))
        pylint_score=$(echo "$pylint_output" | grep -oP '(?<=Your code has been rated at ).*(?=/10)' || true)
        echo "Pylint Score: $pylint_score"
        
        if (( $(echo "$pylint_score > 8.5" | bc -l) )); then
          echo "Check passed successfully!"
        else
          echo "Code quality is below standard. Review the errors below:"
          pylint_errors=$(echo "$pylint_output" | grep -A1 '=== Your code has been rated' || true)
          echo "$pylint_errors"
          exit 1
        fi
