name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pulp
    - name: Analysing the code with pylint
      run: |
        pylint_score=$(pylint --score=y $(git ls-files '*.py') | grep -oP '(?<=Your code has been rated at ).*(?=/10)')
        echo "Оценка Pylint: $pylint_score"
        if (( $(echo "$pylint_score > 7.0" | bc -l) )); then
          echo "Проверка прошла успешно!"
        else
          echo "Пересмотрите код..."
          exit 1 # Добавляем это, чтобы тест проваливался
        fi
