name: Run Unit Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        

    - name: Run unit tests file1
      run: python src/app/tests.py

    - name: Run unit tests file2
      run: python src/modules/test.py

    - name: Run unit tests file3
      run: python src/modules/negativetests.py
